In [1]:
# there are several functions for creating arrays

In [8]:
import numpy as np

a = np.ones((3, 2)) # creates 3X2 array of 1s
b = np.zeros((3, 4)) # creates 3X4 array of 0s
c = np.random.random(3) # creates one-dimentional array of random values
d = np.full((2, 2), 12) # creates 2X2 array filled with the provided value

print(a, b, c, d, sep='\n\n')

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0.92567719 0.68044034 0.76498306]

[[12 12]
 [12 12]]


In [9]:
# we also have the following
# 'np.empty()' for creating an array of uninitialized elements
# 'np.eye()' and 'np.identity()' funcitons  are for creating identity arrays for matrix calculations.

In [10]:
# you can optionally specify the data type for array elements at the time of creation
my_arr = np.full((2, 2), 12, dtype=np.float32)
print(my_arr)

[[12. 12.]
 [12. 12.]]


In [ ]:
# the 'copy()' function creates a copy of an array
# example 'a = b.copy()'

# the 'loadtxt()' function can be used to load data from a file into an array.

# the 'save()' function is used to save a numpy array to a file.