In [1]:
# two useful numpy functions for creating  a list of numbers that fill a range are 'np.arange()'
# and 'np.linspace()'.
# both functions evenly space values. However, the 'np.arrange' function returns values up to the end parameter,
# whereas the 'np.linspace' returns a specified number of elements

In [5]:
# np.arrange(start, end, step)
# it creates a numpy array with elements ranging in value from 'start' to 'end', incrementing by 'step'.

import numpy as np

a = np.arange(0, 10, 2)
print(a)

# only 'end' is required. omiting start and step creates and evenly spaced range from 0 to end.
b = np.arange(6)
print(b)

[0 2 4 6 8]
[0 1 2 3 4 5]


In [6]:
# np.linspace(start, end, numvalues)
# it creates a numpy array with 'numbalues' values evenly spaced from 'start' to 'end'

c = np.linspace(0, 10, 6)
print(c)

[ 0.  2.  4.  6.  8. 10.]
