In [1]:
# a numpy array can be reshaped and resized. reshaping with 
# 'np.reshape' returns a new array with a modified shape
# and resizing with 'np.resize' modifies the original array.
# A third function 'np.ravel' returns a flattened array.

In [3]:
import numpy as np

a = np.arange(10)
print(a.shape)
print(a)

a.resize(2, 5)
print(a.shape)
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b, b.shape,)
print(b.reshape(3, 2))
print(b.shape)
print(b.ravel())# or 'np.ravel(b)'
print(b)

(10,)
[0 1 2 3 4 5 6 7 8 9]
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]__(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(2, 3)
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [4]:
# Note that reshape and ravel do not resize array b from its original shape

In [7]:
# the 'np.transpose()' function transposes an array (matrix transposition. rows become coumns and culumns rows)
import numpy as np
a =np.array([[1, 2, 3], [4, 5, 6]])
print(a, a.transpose(), sep = '\n\n')

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
