In [1]:
# just like with lists, we can slice an array to extract a subset of it
# array slicing refers to the actual array elements. so changing a value in a slice will effect the 
#change in the array itself

In [2]:
# to slice an array, you indicate the 'start:stop:step' of the subset in sqare brackets
# for a multidimensional array, specify the elements for each dimension separated by a comma.
# an ellipsis (...) is used to indicate selection along an entire dimension.

#Examples;

In [8]:
import numpy as np

x = np.arange(8) # 0 1 2 3 4 5 6 7
y = x[0:4] # fist four elements. no step
z = x[6: ] # from the sixth element to the last. no step

print(x, y, z, sep = '\n')
print(x[:5:2])

z[1] = 10 # replaces 7 with 10 in the original array (x)
print(x)

[0 1 2 3 4 5 6 7]
[0 1 2 3]
[6 7]
[0 2 4]
[ 0  1  2  3  4  5  6 10]


In [51]:
a = np.array([[10, 11, 12, 13], [20, 22, 23, 25], [2, 3, 4, 5]])
print(a[0:1, 2]) #0-start dimension , 1-end dimension , 2-index
print(a[..., 1]) # second item from all dimensions
print(a[ : , 3])
print(a[1:3, ])

[12]
[11 22  3]
[13 25  5]
[[20 22 23 25]
 [ 2  3  4  5]]
