In [1]:
# given two numpy arrays, we can carry out some arithmetic calculations on them
# basic operations can use functions by the name. they include; 'add', 'subtract', 'multiply', 'divide' and 'remainder' and 'power'
# arithmetic operators (+, -, *, /, **) can also be used to carry out array operations
# logical comparisons (<, >, ==) can be made, and will return an array of booleans
# The matrix dot product is performed using 'np.dot()'
#examples below

In [7]:
import numpy as np

x = np.array([[1,2,3,4], [5,6,7,8]])
y = np.array([[9,10,11,12], [13,14,15,16]])

print(np.add(x, y))
print(np.remainder(y,x)) # %
print(x**2)
print(y-x)
print(x<5)



[[10 12 14 16]
 [18 20 22 24]]
[[0 0 2 0]
 [3 2 1 0]]
[[ 1  4  9 16]
 [25 36 49 64]]
[[8 8 8 8]
 [8 8 8 8]]
[[ True  True  True  True]
 [False False False False]]
