In [ ]:
'''
Numpy functions that work on an array include

np.sum() Returns the sum of all elements
np.min(), np.max Returns the minimum/maximum value in an array
np.cumsum() Returns the cummulative sum of elements
np.mean(), np.median() Returns the mean/median for and array

for all functions mentioned above, you can include and optional 'axis = 1' parameter for the valude in each row
and 'axis = 0' for columbs

np.corrcoef() Returns the correlation coefficient for the array
np.std() Returns the standard deviation for the array

'''

In [15]:
import numpy as np

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
y = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])

print(x.sum(axis = 0))
print(x.sum(axis = 1), '\n')

print(np.min(x))
print(x.max(axis = 1))
print('\n')

print(np.cumsum(y))
print(np.corrcoef(y))
print(y.std())

[ 6  8 10 12]
[10 26] 

1
[4 8]


[  9  19  30  42  55  69  84 100]
[[1. 1.]
 [1. 1.]]
2.29128784747792
