### Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations
when arithmetic operations on arrays of different sizes are performed, an operation called broadcasting is
performed **to expand the smaller array to match the larger array.**
### Conditions for broadcasting
1. **Arrays have the same dimension**
2. **A corresponding Dimention be 1**

Dimensions that do not match cannot be stretched if one of them is not 1.
in such case, a ValueError will be raised because broadcasting can't make the dimensions match


In [2]:
# EXamples

import numpy as np

one_d = np.array([10])
two_d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
three_d = np.ones((3, 2))


In [3]:
print(np.add(two_d, one_d)) # one_d will be stretched to be as though it were 'np.full((2, 4), 10)'

[[11 12 13 14]
 [15 16 17 18]]


In [5]:
print(np.add(one_d, three_d))

[[11. 11.]
 [11. 11.]
 [11. 11.]]


In [6]:
print(np.add(two_d, three_d)) # NumPy can't stretch either of the arrays hence ValueError

ValueError: operands could not be broadcast together with shapes (2,4) (3,2) 